BNP = BNP or {}

-- Warlock debuffs supported by the SuperWoW own-cast tracker.
-- Durations are Vanilla defaults. Rank-specific values are used where ranks
-- materially change the duration. Server-specific effects such as Dark
-- Harvest are intentionally handled in a later compatibility pass.
BNP.WarlockAuras = {
  {
    key = "corruption",
    names = { "Corruption", "Verderbnis" },
    texture = "Interface\\Icons\\Spell_Shadow_AbominationExplosion",
    textureMatch = "abominationexplosion",
    duration = 18,
    durations = { [172] = 12, [6222] = 15, [6223] = 18, [7648] = 18, [11671] = 18, [11672] = 18 },
  },
  {
    key = "curse_of_agony",
    category = "CURSE",
    names = { "Curse of Agony", "Fluch der Pein" },
    texture = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras",
    textureMatch = "curseofsargeras",
    duration = 24,
    spellIDs = { 980, 1014, 6217, 11711, 11712, 11713 },
  },
  {
    key = "siphon_life",
    names = { "Siphon Life", "Lebensentzug" },
    texture = "Interface\\Icons\\Spell_Shadow_Requiem",
    textureMatch = "requiem",
    duration = 30,
    spellIDs = { 18265, 18879, 18880, 18881 },
  },
  {
    key = "immolate",
    names = { "Immolate", "Feuerbrand" },
    texture = "Interface\\Icons\\Spell_Fire_Immolation",
    textureMatch = "immolation",
    duration = 15,
    spellIDs = { 348, 707, 1094, 2941, 11665, 11667, 11668 },
  },
  {
    key = "curse_of_doom",
    category = "CURSE",
    names = { "Curse of Doom", "Fluch der Verdammnis" },
    texture = "Interface\\Icons\\Spell_Shadow_AuraOfDarkness",
    textureMatch = "auraofdarkness",
    duration = 60,
    spellIDs = { 603, 30910 },
  },
  {
    key = "curse_of_weakness",
    category = "CURSE",
    names = { "Curse of Weakness", "Fluch der Schwäche" },
    texture = "Interface\\Icons\\Spell_Shadow_CurseOfMannoroth",
    textureMatch = "curseofmannoroth",
    duration = 120,
    spellIDs = { 702, 1108, 6205, 7646, 11707, 11708 },
  },
  {
    key = "curse_of_recklessness",
    category = "CURSE",
    names = { "Curse of Recklessness", "Fluch der Tollkühnheit" },
    texture = "Interface\\Icons\\Spell_Shadow_UnholyStrength",
    textureMatch = "unholystrength",
    duration = 120,
    spellIDs = { 704, 7658, 7659, 11717 },
  },
  {
    key = "curse_of_tongues",
    category = "CURSE",
    names = { "Curse of Tongues", "Fluch der Sprachen" },
    texture = "Interface\\Icons\\Spell_Shadow_CurseOfTounges",
    textureMatch = "curseoftounges",
    duration = 30,
    spellIDs = { 1714, 11719 },
  },
  {
    key = "curse_of_elements",
    category = "CURSE",
    names = { "Curse of the Elements", "Curse of Elements", "Fluch der Elemente" },
    texture = "Interface\\Icons\\Spell_Shadow_ChillTouch",
    textureMatch = "chilltouch",
    duration = 300,
    spellIDs = { 1490, 11721, 11722 },
  },
  {
    key = "curse_of_shadow",
    category = "CURSE",
    names = { "Curse of Shadow", "Fluch der Schatten" },
    texture = "Interface\\Icons\\Spell_Shadow_CurseOfAchimonde",
    textureMatch = "curseofachimonde",
    duration = 300,
    spellIDs = { 17862, 17937 },
  },
  {
    key = "curse_of_exhaustion",
    category = "CURSE",
    names = { "Curse of Exhaustion", "Fluch der Erschöpfung" },
    texture = "Interface\\Icons\\Spell_Shadow_GrimWard",
    textureMatch = "grimward",
    duration = 12,
    spellIDs = { 18223 },
  },
  {
    key = "fear",
    names = { "Fear", "Furcht" },
    texture = "Interface\\Icons\\Spell_Shadow_Possession",
    textureMatch = "possession",
    duration = 20,
    durations = { [5782] = 10, [6213] = 15, [6215] = 20 },
  },
  {
    key = "howl_of_terror",
    names = { "Howl of Terror", "Schreckensgeheul" },
    texture = "Interface\\Icons\\Spell_Shadow_DeathScream",
    textureMatch = "deathscream",
    duration = 15,
    durations = { [5484] = 10, [17928] = 15 },
  },
  {
    key = "banish",
    names = { "Banish", "Verbannen" },
    texture = "Interface\\Icons\\Spell_Shadow_Cripple",
    textureMatch = "cripple",
    duration = 30,
    durations = { [710] = 20, [18647] = 30 },
  },
  {
    key = "death_coil",
    names = { "Death Coil", "Todesmantel" },
    texture = "Interface\\Icons\\Spell_Shadow_DeathCoil",
    textureMatch = "deathcoil",
    duration = 3,
    spellIDs = { 6789, 17925, 17926 },
  },
  {
    key = "drain_life",
    channel = true,
    names = { "Drain Life", "Blutsauger" },
    texture = "Interface\\Icons\\Spell_Shadow_LifeDrain02_Purple",
    textureMatch = "lifedrain02",
    duration = 5,
    spellIDs = { 689, 699, 709, 7651, 11699, 11700 },
  },
  {
    key = "drain_soul",
    channel = true,
    names = { "Drain Soul", "Seelendieb" },
    texture = "Interface\\Icons\\Spell_Shadow_Haunting",
    textureMatch = "haunting",
    duration = 15,
    spellIDs = { 1120, 8288, 8289, 11675 },
  },
  {
    key = "enslave_demon",
    names = { "Enslave Demon", "Dämonensklave" },
    texture = "Interface\\Icons\\Spell_Shadow_EnslaveDemon",
    textureMatch = "enslavedemon",
    duration = 300,
    spellIDs = { 1098, 11725, 11726 },
  },
  {
    key = "shadow_vulnerability",
    names = { "Shadow Vulnerability" },
    duration = 10,
    spellIDs = { 17794, 17797, 17798, 17799, 17800 },
    -- Shadow Vulnerability uses a different aura spell ID for each talent rank.
    -- Track every rank so BNP also sees/refreshes Rank 5 [17800].
    shared = true,
    sharedSpellIDs = { 17794, 17797, 17798, 17799, 17800 },
  },
}
